/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-08-17 05:33:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class flicker_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div id=\"flicker\" class=\"carousel slide flicker\" data-ride=\"carousel\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Indicators -->\r\n");
      out.write("\r\n");
      out.write("\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t<li data-target=\"#flicker\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#flicker\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#flicker\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#flicker\" data-slide-to=\"3\"></li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Wrapper for slides -->\r\n");
      out.write("\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"slide1\" class=\"item active\" style=\"background-image: url('jsp/layout/images/bg-services.jpg');\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- \t<img src=\"jsp/layout/images/bg-services.jpg\" alt=\"Joker vs Batman\"> -->\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<p> All rise for the King </p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"item\" style=\"background-image: url('jsp/layout/images/debate.jpg');\">\r\n");
      out.write("\t\t\t\t<img src=\"jsp/layout/images/debate.jpg\" alt=\"TDKR\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<p> And I thought my jokes were Bad </p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <div class=\"item\" style=\"background-image: url('jsp/layout/images/tdk3.jpg');\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<img src=\"jsp/layout/images/skeletal-debate-1.jpg\" alt=\"TDKR\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<p> start debate  </p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"item\" style=\"background-image: url('jsp/layout/images/jaguar.jpg');\">\r\n");
      out.write("\t\t\t\t<img src=\"jsp/layout/images/jaguar.jpg\" alt=\"jaguar\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t<p>Tag Clouds also</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Controls -->\r\n");
      out.write("\t\t<a class=\"left carousel-control\" href=\"#flicker\" role=\"button\" data-slide=\"prev\"> \r\n");
      out.write("\t\t\t<span class=\"glyphicon glyphicon-chevron-left\"></span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t <a class=\"right carousel-control\" href=\"#flicker\" role=\"button\" data-slide=\"next\"> \r\n");
      out.write("\t\t\t <span class=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
