/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-08-17 05:33:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"margin: 0px -10px 0px -10px;\">\r\n");
      out.write("\t<div class=\"container-fluid\"\r\n");
      out.write("\t\tstyle=\"background-color: #333; padding-bottom: 10px; text-align: center;\">\r\n");
      out.write("\t\t<div class=\"row\" style=\"margin: 20px\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h3 style=\"color: #7e7e7e;\">About the website</h3>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3\" style=\"text-align: center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"center\">\r\n");
      out.write("\t\t\t\t\t<h4 style=\"color: #7e7e7e;\">Reach Us</h4>\r\n");
      out.write("\t\t\t\t\t<ul class=\"uList\" style=\"text-align: left; padding-left: 68px;\">\r\n");
      out.write("\t\t\t\t\t\t<li>Salt Lake City</li>\r\n");
      out.write("\t\t\t\t\t\t<li>Kolkata 700091</li>\r\n");
      out.write("\t\t\t\t\t\t<li>West Bengal</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-4  col-md-offset-1\">\r\n");
      out.write("\t\t\t\t<h4 style=\"color: #7e7e7e;\">Subscribe for Newsletter</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"text\"\r\n");
      out.write("\t\t\t\t\tonfocus=\"if(this.value=='you@youremail.com'){this.value=''};\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background-color: #333; text-align: center; margin-left: 80px;\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\"\r\n");
      out.write("\t\t\t\t\tonblur=\"if(this.value==''){this.value='you@youremail.com'};\"\r\n");
      out.write("\t\t\t\t\tonkeyup=\"if(event.keyCode == 13){send_newsletter();}\"\r\n");
      out.write("\t\t\t\t\tvalue=\"you@youremail.com\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h5 style=\"padding-right: 25px;\">Sitemap</h5>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t<h4>DexLock Inc.</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"uList\" style=\"text-align: right;padding-right: 159px;\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\"> About the Company </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\"> About the Developers </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\"> Read DexLock Blog </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\"\r\n");
      out.write("\t\tstyle=\"background-color: #222222; margin: 0px 0px -10px -10px;\">\r\n");
      out.write("\t\t<div class=\"row\" style=\"text-align: center; padding: 10px;\">\r\n");
      out.write("\t\t\t<div class=\"col-md-4\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"\"><img width=\"26\" height=\"25\" border=\"0\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Facebook\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jsp/layout/images/i-facebook.png\"> </a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"\"><img width=\"26\" height=\"25\" border=\"0\" alt=\"Twitter\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jsp/layout/images/i-twitter.png\"> </a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tAll Rights Reserved © 2014 Dexlock Inc. <a\r\n");
      out.write("\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/HomePage\">canyoudebate.com</a> <a href=\"#\">Privacy</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">Terms</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-4\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /jsp/layout/footer.jsp(2,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("contextPath");
    // /jsp/layout/footer.jsp(2,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/jsp/layout/footer.jsp(2,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
