/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-08-17 06:41:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.modules.debate;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class debate_002dgame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div ng-controller=\"debateGameController\" onload=\"document.getElementById('debateHome').reset()\">\r\n");
      out.write("\t\r\n");
      out.write("<div id=\"topicTitle\" class=\"hero-unit\"\r\n");
      out.write("\t\tstyle=\"margin-top: 50px; margin-bottom: 2px; padding: 19px;\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"span5\">Topic for the Debate :</div>\r\n");
      out.write("\t\t\t\t<div class=\"span7 topicFont\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SelectedTopic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"debateHome\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"hero-unit\" style=\"padding: 10px;\">\r\n");
      out.write("\t\t\t<a id=\"teamA\" href=\"\" style=\"padding-left: 300px;\" ng-click=\"selectTeam('A')\">Team A (For)</a>\r\n");
      out.write("\t\t\t<span id=\"selectOneTeam\"  style=\"padding-left: 195px;\">Select A Team</span>\r\n");
      out.write("\t\t\t<a id=\"teamB\" href=\"\"\tstyle=\"padding-left: 225px;\" ng-click=\"selectTeam('B')\">Team B (Against)</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"width: 100%; padding-left: 20px;\">\r\n");
      out.write("\t\t\t<form id=\"forForm\">\r\n");
      out.write("\t\t\t\t<div id=\"for\" class=\"table-responsive for\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table\" style=\"height: 300px\">\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr ng-repeat=\"forDataList in forRows track by $index\" style=\"height: 50px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>{{forDataList}}</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea id=\"forText\" class=\"field col-md-6 form-control \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trows=\"6\" placeholder=\"Enter a short comment\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"resize: none\" ng-keypress=\"addForComments($event)\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"vertical-line\">\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form id=\"againstForm\">\r\n");
      out.write("\t\t\t\t<div id=\"against\" class=\"table-responsive against\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table\" style=\"height: 300px\">\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr ng-repeat=\"againstDataList in againstRows track by $index\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"height: 50px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>{{againstDataList}}</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div class=\"span6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea id=\"againstText\" class=\"field col-md-6 form-control \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trows=\"6\" placeholder=\"Enter a short comment\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"resize: none\" ng-keypress=\"addAgainstComments($event)\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
